<?php
// $Id$

/**
 * Implements hook_theme().
 */
function form_embed_blks_theme() {
  $base = array(
    'file' => 'form_embed_blks.theme.inc',
    'path' => drupal_get_path('module', 'form_embed_blks') . '/tpl',
  );
  return array(
    'jcpl_ill_request' => array(
      'template' => 'jcpl-ill-request',
    ) + $base,
	    'jcpl_suggest_title' => array(
      'template' => 'jcpl-suggest-title',
    ) + $base,
		'jcpl_contact_us' => array(
      'template' => 'jcpl-contact-us',
    ) + $base,
	    'jcpl_email_librarian' => array(
      'template' => 'jcpl-email-librarian',
    ) + $base,
	    'jcpl_email_librarian_sidebar' => array(
      'template' => 'jcpl-email-librarian-sidebar',
    ) + $base,
		'jcpl_book_librarian' => array(
      'template' => 'jcpl-book-librarian',	 
    ) + $base,
		'jcpl_book_librarian_feedback' => array(
      'template' => 'jcpl-book-librarian-feedback',	   
    ) + $base,
	  'jcpl_volunteer' => array(
      'template' => 'jcpl-volunteer',
    ) + $base,
      'jcpl_PRR_form' => array(
      'template' => 'jcpl-PRR-form',
    ) + $base,
	  'jcpl_advocates' => array(
      'template' => 'jcpl-advocates',
    ) + $base,
      'jcpl_newsletter' => array(
      'template' => 'jcpl-newsletter',
    ) + $base,
      'jcpl_pmsurvey' => array(
      'template' => 'jcpl-pmsurvey',
    ) + $base,
	
  );
}

/**
 * Implements hook_block_info().
 */
function form_embed_blks_block_info() {
  $blocks = array();
  
   $blocks['ill_request' ] = array(
    'info' => t('Didnt find it: Request an interlibrary loan'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'books-movies-music/interlibrary-loan',
   );
  
   $blocks['suggest_title'] = array(
    'info' => t('Didnt find it: Suggest a title'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'books-movies-music/suggest-title',
   );

   $blocks['contact_us'] = array(
    'info' => t('Contact Us: form'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'contact-us',
   );

   $blocks['email_librarian'] = array(
    'info' => t('Ask Us: Email a Librarian'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'ask-us/email-librarian',
   );

 $blocks['email_librarian_sidebar'] = array(
    'info' => t('Email Us'),
    'status' => 1,
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'ask-us',
   );

    $blocks['book_librarian'] = array(
    'info' => t('Ask Us: Book a Librarian'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'ask-us/book-librarian',
   );
   
    $blocks['book_librarian_feedback'] = array(
    'info' => t('Ask Us: Book a Librarian - Feedback'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'ask-us/book-librarian-feedback',
   );
   
   $blocks['volunteer'] = array(
    'info' => t('Volunteer'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'volunteer/volunteer-now',
   );
   
   $blocks['PRR_form'] = array(
    'info' => t('BMM: Your Next 5 Books'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'books-movies-music/your-next-5-books',
   );  
   
    $blocks['advocates'] = array(
    'info' => t('Directors Blog: Email sign up'),
    'status' => 1,
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'directors-blog',
   );    
   
    $blocks['newsletter'] = array(
    'info' => t('Library News: Email sign up'),
    'status' => 1,
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'library-news',
   );
      
    $blocks['pmsurvey'] = array(
    'info' => t('Events: PM Survey form'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'events/pm-survey',
   );                
	return $blocks;
}   
  
/**
 * Implements hook_block_view().
 */
function form_embed_blks_block_view($block_name = '') {
	 
   if ($block_name == 'ill_request') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_ill_request'),
    );
	
    return $block;
  }
  
      if ($block_name == 'suggest_title') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_suggest_title'),
    );
	
    return $block;
  }
    
      if ($block_name == 'contact_us') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_contact_us'),
    );
	
    return $block;
  }
  
        if ($block_name == 'email_librarian') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_email_librarian'),
    );
	
    return $block;
  } 

        if ($block_name == 'email_librarian_sidebar') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_email_librarian_sidebar'),
    );
	
    return $block;
  } 

        if ($block_name == 'book_librarian') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_book_librarian'),
    );
	
    return $block;
  } 

        if ($block_name == 'book_librarian_feedback') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_book_librarian_feedback'),
    );
	
    return $block;
  } 
              
        if ($block_name == 'volunteer') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_volunteer'),
    );
	
    return $block;
  }
  
   if ($block_name == 'PRR_form') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_PRR_form'),
    );
	
    return $block;
  }
  
   if ($block_name == 'advocates') {
    $block = array(
      'subject' => t('Receive email updates'),
      'content' => theme('jcpl_advocates'),
    );
	
    return $block;
  }

   if ($block_name == 'newsletter') {
    $block = array(
      'subject' => t('Sign up for Library News'),
      'content' => theme('jcpl_newsletter'),
    );
	
    return $block;
  }
    
     if ($block_name == 'pmsurvey') {
    $block = array(
      'subject' => t(''),
      'content' => theme('jcpl_pmsurvey'),
    );
	
    return $block;
  }
}