<?php
// $Id$

/**
 * Implements hook_block_info().
 */

function footer_blks_block_info() {
  $blocks = array();
	
    $blocks['footer_aboutus'] = array(
      'info' => t('Footer: About Us.'),
      'status' => 1,
	  'region' => 'footer_first',
    );
	
    $blocks['footer_services'] = array(
      'info' => t('Foooter: Services.'),
      'status' => 1,
	  'region' => 'footer_second',
    );
	
	$blocks['footer_support'] = array(
      'info' => t('Footer: Support the Library.'),
      'status' => 1,
	  'region' => 'footer_third',
    );
  
	return $blocks;
}


/**
 * Implements hook_block_view().
 */
function footer_blks_block_view($block_name = '') {

  if ($block_name == 'footer_aboutus') {
	  
    global $base_url ; 
  
    $content = "<ul class=\"menu\"><li><a href=\"$base_url/board-of-trustees\" title=\"Board of Trustees\">Board of Trustees</a></li>
<li><a href=\"$base_url/jobs\" title=\"Jobs\">Jobs</a></li>
<li><a href=\"$base_url/leadership-mission\" title=\"Leadership and Mission\">Leadership &amp; Mission</a></li>
<li><a href=\"$base_url/planning-budget\" title=\"Planning and Budget\">Planning &amp; Budget</a></li>
<li><a href=\"$base_url/policies\" title=\"Policies\">Policies</a></li>
<li><a href=\"$base_url/press-room\" title=\"Press Room\">Press Room</a></li>
</ul>";

    $block = array(
      'subject' => t('About Us'),
      'content' => $content,
    );

    return $block;
  }
  
  if ($block_name == 'footer_services') {
	  
    global $base_url ; 
  
    $content = "<ul class=\"menu\"><li><a href=\"$base_url/ask-us\" title=\"Ask Us\">Ask Us</a></li>
<li><a href=\"$base_url/culture-pass\" title=\"Culture Pass\">Culture Pass</a></li>
<li><a href=\"$base_url/get-library-card\" title=\"Get a Library Card\">Get a Library Card</a></li>
<li><a href=\"$base_url/outreach-services\" title=\"Outreach Services\">Outreach Services</a></li>
<li><a href=\"$base_url/recursos-en-espa%C3%B1ol\" title=\"Recuroso en Espanol\">Recursos en Espa&ntilde;ol</a></li>
<li><a href=\"$base_url/reserve-computer\" title=\"Reserve a Computer\">Reserve a Computer</a></li>
<li><a href=\"$base_url/wireless\" title=\"Wireless\">Wireless</a></li>
</ul>";

    $block = array(
      'subject' => t('Services'),
      'content' => $content,
    );

    return $block;
  }

  if ($block_name == 'footer_support') {
  
    global $base_url ; 

    $content = "<ul class=\"menu\"><li><a href=\"$base_url/community-partners\" title=\"Community Partners\">Community Partners</a></li>
<li><a href=\"$base_url/directors-blog\" title=\"Directors Blog\">Director&#039;s Blog</a></li>
<li><a href=\"http://jeffcolibraryfoundation.org\" title=\"Donate\">Donate</a></li>
<li><a href=\"http://jeffcolibraryfoundation.org\" title=\"Foundation and Friends\">Foundation &amp; Friends</a></li>
<li><a href=\"$base_url/request-speaker\" title=\"Request a Speaker\">Request a Speaker</a></li>
<li><a href=\"$base_url/volunteer\" title=\"Volunteer\">Volunteer</a></li>
</ul>";

    $block = array(
      'subject' => t('Support the Library'),
      'content' => $content,
    );

    return $block;
  }
  

}