<?php
// $Id$

/**
 * Implements hook_block_info().
 */

function footer_blks_block_info() {
  $blocks = array();
	
    $blocks['footer_aboutus'] = array(
      'info' => t('Footer: About Us.'),
      'status' => 1,
	  'region' => 'footer_first',
    );
	
    $blocks['footer_services'] = array(
      'info' => t('Foooter: Services.'),
      'status' => 1,
	  'region' => 'footer_second',
    );
	
	$blocks['footer_support'] = array(
      'info' => t('Footer: Support the Library.'),
      'status' => 1,
	  'region' => 'footer_third',
    );
	
	$blocks['footer_connect'] = array(
    'info' => t('Footer: Connect with Us.'),
    'status' => 1,
    'region' => 'footer_fourth',
    );

    $blocks['footer_copyright'] = array(
    'info' => t('Footer: Copyright.'),
    'status' => 1,
    'region' => 'footer_fifth',
    );

    $blocks['footer_address_phone'] = array(
    'info' => t('Footer: Address, phone number, contatct us.'),
    'status' => 1,
    'region' => 'footer_fifth',
    );

    $blocks['board_join'] = array(
    'info' => t('Board of Trustees: Join our board.'),
    'status' => 1,
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_LISTED,
	'pages' => 'board-of-trustees',
    );

    $blocks['media_contacts'] = array(
    'info' => t('Press Room: Media Contacts.'),
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
	'pages' => 'press-room',
    );

	return $blocks;
}


/**
 * Implements hook_block_view().
 */
function footer_blks_block_view($block_name = '') {

  if ($block_name == 'footer_aboutus') {
	  
    global $base_url ; 
  
    $content = "<ul class=\"menu\"><li><a href=\"$base_url/board-of-trustees\" title=\"Board of Trustees\">Board of Trustees</a></li>
<li><a href=\"$base_url/jobs\" title=\"Jobs\">Jobs</a></li>
<li><a href=\"$base_url/leadership-mission\" title=\"Leadership and Mission\">Leadership &amp; Mission</a></li>
<li><a href=\"$base_url/library-news\" title=\"Library News\">Library News</a></li>
<li><a href=\"$base_url/planning-budget\" title=\"Planning and Budget\">Planning &amp; Budget</a></li>
<li><a href=\"$base_url/policies\" title=\"Policies\">Policies</a></li>
<li><a href=\"$base_url/press-room\" title=\"Press Room\">Press Room</a></li>
</ul>";

    $block = array(
      'subject' => t('About Us'),
      'content' => $content,
    );

    return $block;
  }
  
  if ($block_name == 'footer_services') {
	  
    global $base_url ; 
  
    $content = "<ul class=\"menu\"><li><a href=\"$base_url/ask-us\" title=\"Ask Us\">Ask Us</a></li>
<li><a href=\"$base_url/culture-pass\" title=\"Culture Pass\">Culture Pass</a></li>
<li><a href=\"$base_url/get-library-card\" title=\"Get a Library Card\">Get a Library Card</a></li>
<li><a href=\"$base_url/outreach-services\" title=\"Outreach Services\">Outreach Services</a></li>
<li><a href=\"$base_url/recursos-en-espa%C3%B1ol\" title=\"Recuroso en Espanol\">Recursos en Espa&ntilde;ol</a></li>
<li><a href=\"$base_url/reserve-computer\" title=\"Reserve a Computer\">Reserve a Computer</a></li>
<li><a href=\"$base_url/wireless\" title=\"Wireless\">Wireless</a></li>
</ul>";

    $block = array(
      'subject' => t('Services'),
      'content' => $content,
    );

    return $block;
  }

  if ($block_name == 'footer_support') {
  
    global $base_url ; 

    $content = "<ul class=\"menu\"><li><a href=\"$base_url/community-partners\" title=\"Community Partners\">Community Partners</a></li>
<li><a href=\"$base_url/directors-blog\" title=\"Directors Blog\">Director&#039;s Blog</a></li>
<li><a href=\"http://jeffcolibraryfoundation.org\" title=\"Donate\">Donate</a></li>
<li><a href=\"http://jeffcolibraryfoundation.org\" title=\"Foundation and Friends\">Foundation &amp; Friends</a></li>
<li><a href=\"$base_url/request-speaker\" title=\"Request a Speaker\">Request a Speaker</a></li>
<li><a href=\"$base_url/volunteer\" title=\"Volunteer\">Volunteer</a></li>
</ul>";

    $block = array(
      'subject' => t('Support the Library'),
      'content' => $content,
    );

    return $block;
  }
  
  if ($block_name == 'footer_connect') {

    global $base_url ;

    $content = "<div id=\"social_media_icons\"><a href=\"http://www.facebook.com/JeffersonCountyPublicLibrary\"><img src=\"$base_url/sites/default/files/head_foot/facebook.png\" width=\"40\" height=\"40\" alt=\"Facebook\" /></a>
	<a href=\"http://www.twitter.com/JCPL\"><img src=\"$base_url/sites/default/files/head_foot/twitter.png\" width=\"40\" height=\"40\" alt=\"Twitter\" /></a>
	<a href=\"http://vimeo.com/jcpl\"><img src=\"$base_url/sites/default/files/head_foot/vimeo.png\" width=\"40\" height=\"40\" alt=\"Vimeo\" /></a>
	<a href=\"http://www.youtube.com/jcplcolorado\"><img src=\"$base_url/sites/default/files/head_foot/youtube.png\" width=\"40\" height=\"40\" alt=\"You Tube\" /></a></div>
	<!-- <form id=\"form1\" name=\"form1\" method=\"post\" action=\"\">
	  Sign up for our newsletter<br />
	<input type=\"text\" name=\"textfield\" id=\"textfield\" />
	</form> -->";

    $block = array(
	'subject' => t('Connect with Us'),
	'content' => $content,
    );

    return $block;
  }

  if ($block_name == 'footer_copyright') {

    $content = '<p>&copy;2013 Jefferson County Public Library</p>';

    $block = array(
	'subject' => t(''),
	'content' => $content,
    );

    return $block;
  }

  if ($block_name == 'footer_address_phone') {

    global $base_url ; 

    $content = "10200 W. 20th Ave, Lakewood, CO 80215<br />
	303-235-JCPL (5275)<br />
	<a href=\"$base_url/site-index\">Site Index</a> | <a href=\"$base_url/contact\">Contact Us</a>";

    $block = array(
	'subject' => t(''),
	'content' => $content,
    );

    return $block;
  }
  
  if ($block_name == 'board_join') {
	  
    global $base_url ; 
  
    $content = "<ul>
  <li><a href=\"http://jeffco.us/bcc/bcc_T25_R20.htm\">How to Join</a></li>
  <li><a href=\"$base_url/board-of-trustees/responsibilities\">Responsibilities</a></li>
  <li><a href=\"$base_url/board-of-trustees/ends-statement\">Ends Statement</a></li>
</ul>";

    $block = array(
      'subject' => t('Join Our Board'),
      'content' => $content,
    );

    return $block;
  }

  if ($block_name == 'media_contacts') {
	  
    global $base_url ; 
  
    $content = "<div class=\"media_contact\"><a href=\"mailto:rebecca.winning@jeffcolibrary.org\">Rebecca Winning</a><br />Director of Communications<br />303-275-2203</div>
	<div class=\"media_contact\"><a href=\"mailto:bethany.frisbie@jeffcolibrary.org\">Bethany Frisbie</a><br />Promotions &amp; Marketing Manager<br />303-275-2234</div>
	<a href=\"$base_url/contact\">Contact Us</a>";

    $block = array(
      'subject' => t('Media Contacts'),
      'content' => $content,
    );

    return $block;
  }

}