<?php
// $Id$

/**
 * Implements hook_block_info().
 */
function jeffcolibrary_blks_block_info() {
  $blocks = array();

    $blocks['encore_search'] = array(
    'info' => t('Encore Search for header Quicktabs.'),
    'status' => 1,
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function jeffcolibrary_blks_block_view($block_name = '') {

    if ($block_name == 'encore_search') {
  
    $content = '<form method="get" action="http://encore.jefferson.lib.co.us/iii/encore/Home,$Search.form.sdirect" name="form" id="form">	
      <div style="height:0px;">
      <input name="formids" value="target" type="hidden">
      <input name="lang" value="eng" type="hidden">
      <input name="suite" value="def" type="hidden">
      <input name="reservedids" value="lang,suite" type="hidden">
      <input name="submitmode" value="" type="hidden">
      <input name="submitname" value="" type="hidden">
      </div>
      <div id="encore_searchform">
      <input name="target" value="" id="target" size="36" type="text"> 
      <input type="submit" value="Search"/>
      </div>
      <a href="http://encore.jefferson.lib.co.us/iii/encore/home?lang=eng&suite=cobalt&advancedSearch=true&searchString=">Advanced Search</a>
      </form>';

    $block = array(
      'subject' => t('Encore Search'),
      'content' => $content,
    );

    return $block;
  }

}