<?php
// $Id$

/**
 * Implements hook_block_info().
 */
function jeffcolibrary_blks_block_info() {
  $blocks = array();

    $blocks['encore_search'] = array(
    'info' => t('Encore Search for header Quicktabs.'),
    'status' => 1,
  );

    $blocks['sign_in'] = array(
    'info' => t('Homepage Sign In for the ILS.'),
    'status' => 1,
    'region' => 'sidebar_second',
  );
  
    $blocks['locations'] = array(
    'info' => t('Homepage Locations. Links to location pages.'),
    'status' => 1,
    'region' => 'sidebar_second',
  );


  return $blocks;

}


/**
 * Implements hook_block_view().
 */
function jeffcolibrary_blks_block_view($block_name = '') {

    if ($block_name == 'encore_search') {
  
    $content = '<form method="get" action="http://encore.jefferson.lib.co.us/iii/encore/Home,$Search.form.sdirect" name="form" id="form">	
      <div style="height:0px;">
      <input name="formids" value="target" type="hidden">
      <input name="lang" value="eng" type="hidden">
      <input name="suite" value="def" type="hidden">
      <input name="reservedids" value="lang,suite" type="hidden">
      <input name="submitmode" value="" type="hidden">
      <input name="submitname" value="" type="hidden">
      </div>
      <div id="encore_searchform">
      <input name="target" value="" id="target" size="40" type="text"> 
      <input type="submit" value="Search"/>
      </div>
      <a href="http://encore.jefferson.lib.co.us/iii/encore/home?lang=eng&suite=cobalt&advancedSearch=true&searchString=">Advanced Search</a>
      </form>';

    $block = array(
      'subject' => t('Encore Search'),
      'content' => $content,
    );

    return $block;
  }
  
    if ($block_name == 'sign_in') {
  
    $content = '<form id="fm1" class="fm-v clearfix" method="post" action="http://encore.jefferson.lib.co.us/iii/cas/login?service=http%3A%2F%2Fencore.jefferson.lib.co.us%3A80%2Fiii%2Fencore%2Fj_acegi_cas_security_check&amp;lang=eng">

	<!-- Message from client webapp to be displayed on the CAS login screen -->
  	<div id="clientmessage">
	<!--display any errors-->
	
		
  	</div> <!-- end clientmessage -->

	<!--display ldap if avail-->
	
	<!--display login form-->
	<div id="login">
	  <fieldset>
	    <legend>Login Form</legend>
	      <!-- Congratulations on bringing the Login Application online!  The default authentication handler authenticates where usernames equal passwords: go ahead, try it out.   -->
	      <!--<h2>Enter your credentials</h2> -->
	      
	        <div class="name">
	          <label for="name">Name:</label>
	          
	          <input id="name" name="name" class="required" tabindex="3" accesskey="n" type="text" value="" size="20" maxlength="40"/>
	        </div><!-- end name -->
	      
	      
		      <div class="code">
		        <label for="code">Barcode:</label>
		        
		        
		        
		        	
		        		<input id="code" name="code" class="required" tabindex="4" accesskey="b" type="password" value="" size="20" maxlength="40"/>
		        	
		        	
		        
		      </div> <!-- end code -->
		  
	      
	      <!--display pin if required-->
	      
	  	  
		  <!-- Spring Web Flow requirements -->
	      <input type="hidden" name="lt" value="_c3886ABD1-7A7B-B655-57D4-112FB29384F6_k2D8C6128-DB96-CB9A-58C1-FFD9DCA0ECF5" />
	      <input type="hidden" name="_eventId" value="submit" />
	  </fieldset>
	</div>  <!-- end login -->
    <div class="submit">
    	
      		
      		
      			<input class="btn-submit" accesskey="l" value="LOGIN" tabindex="9" type="submit" />
      		
	    
  	</div>
</form>';

    $block = array(
      'subject' => t('Sign In'),
      'content' => $content,
    );

    return $block;
  }

    if ($block_name == 'locations') {
  
    $content = '<div style="width:100px; float:left;">Arvada<br />Belmar<br />Columbine<br />Conifer<br />Edgewater</div>
	  <div style="width: 100px; float:right;">Evergreen<br />Golden<br />Lakewood<br />Standley Lake<br />Wheat Ridge</div>';

    $block = array(
      'subject' => t('Locations'),
      'content' => $content,
    );

    return $block;
  }

}