<?php
/**
 * @file
 * feature_events_highlights.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function feature_events_highlights_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'event_highlights_';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Event Highlights ';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Event Highlights ';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_text'] = 'read more...';
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'node';
  /* Relationship: Content: Taxonomy terms on node */
  $handler->display->display_options['relationships']['term_node_tid']['id'] = 'term_node_tid';
  $handler->display->display_options['relationships']['term_node_tid']['table'] = 'node';
  $handler->display->display_options['relationships']['term_node_tid']['field'] = 'term_node_tid';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  /* Sort criterion: Content: Post date */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'node';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['use_more'] = TRUE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['use_more_text'] = 'read more...';
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'ds';
  $handler->display->display_options['row_options']['view_mode'] = 'full';
  $handler->display->display_options['row_options']['load_comments'] = 0;
  $handler->display->display_options['row_options']['alternating'] = 0;
  $handler->display->display_options['row_options']['grouping'] = 0;
  $handler->display->display_options['row_options']['advanced'] = 0;
  $handler->display->display_options['row_options']['delta_fieldset']['delta_fields'] = array();
  $handler->display->display_options['row_options']['grouping_fieldset']['group_field'] = 'node|created';
  $handler->display->display_options['row_options']['default_fieldset']['view_mode'] = 'full';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  $handler->display->display_options['path'] = 'event-highlights';

  /* Display: Event Highlights Teaser block */
  $handler = $view->new_display('block', 'Event Highlights Teaser block', 'block');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Event Highlights';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['use_more'] = TRUE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '3';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  $handler->display->display_options['block_description'] = 'Events: Highlights teaser block';

  /* Display: Arvada block */
  $handler = $view->new_display('block', 'Arvada block', 'block_1');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Arvada library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '21',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Arvada highlights teaser block';

  /* Display: Belmar block */
  $handler = $view->new_display('block', 'Belmar block', 'block_2');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Arvada library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '22',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Belmar highlights teaser block';

  /* Display: Columbine block */
  $handler = $view->new_display('block', 'Columbine block', 'block_3');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Columbine library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '23',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Columbine highlights teaser block';

  /* Display: Conifer block */
  $handler = $view->new_display('block', 'Conifer block', 'block_4');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Conifer library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '24',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Conifer highlights teaser block';

  /* Display: Edgewater block */
  $handler = $view->new_display('block', 'Edgewater block', 'block_5');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Edgewater library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '25',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Edgewater highlights teaser block';

  /* Display: Evergreen block */
  $handler = $view->new_display('block', 'Evergreen block', 'block_6');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Evergreen library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '26',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Evergreen highlights teaser block';

  /* Display: Golden block */
  $handler = $view->new_display('block', 'Golden block', 'block_7');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Golden library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '28',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Golden highlights teaser block';

  /* Display: Lakewood block */
  $handler = $view->new_display('block', 'Lakewood block', 'block_8');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Lakewood library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '27',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Lakewood highlights teaser block';

  /* Display: Standley Lake block */
  $handler = $view->new_display('block', 'Standley Lake block', 'block_9');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Standley library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '29',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Standley Lake highlights teaser block';

  /* Display: Wheat Ridge block */
  $handler = $view->new_display('block', 'Wheat Ridge block', 'block_10');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = '<none>';
  $handler->display->display_options['display_description'] = 'Event highlights teaser for Standley library';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  /* Filter criterion: Content: Locations tag (field_locations_tag) */
  $handler->display->display_options['filters']['field_locations_tag_tid']['id'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['table'] = 'field_data_field_locations_tag';
  $handler->display->display_options['filters']['field_locations_tag_tid']['field'] = 'field_locations_tag_tid';
  $handler->display->display_options['filters']['field_locations_tag_tid']['value'] = array(
    0 => '31',
    1 => '30',
  );
  $handler->display->display_options['filters']['field_locations_tag_tid']['vocabulary'] = 'locations';
  $handler->display->display_options['block_description'] = 'Events: Wheat Ridge highlights teaser block';

  /* Display: Event Highlights Teaser block */
  $handler = $view->new_display('block', 'Event Highlights Teaser block', 'block_11');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Event Highlights';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['use_more'] = TRUE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '3';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '55',
    1 => '53',
    2 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  $handler->display->display_options['block_description'] = 'Events: Highlights teaser block';

  /* Display: Kids Event Highlights Teaser block */
  $handler = $view->new_display('block', 'Kids Event Highlights Teaser block', 'block_12');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Event Highlights';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['use_more'] = TRUE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '3';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '53',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  $handler->display->display_options['block_description'] = 'Kids: Event Highlights';

  /* Display: Teen Event Highlights Teaser block */
  $handler = $view->new_display('block', 'Teen Event Highlights Teaser block', 'block_13');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'Event Highlights';
  $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
  $handler->display->display_options['defaults']['use_more'] = FALSE;
  $handler->display->display_options['use_more'] = TRUE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['defaults']['use_more_always'] = FALSE;
  $handler->display->display_options['use_more_always'] = TRUE;
  $handler->display->display_options['defaults']['use_more_text'] = FALSE;
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '3';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Select media image */
  $handler->display->display_options['fields']['field_blog_image']['id'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['table'] = 'field_data_field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['field'] = 'field_blog_image';
  $handler->display->display_options['fields']['field_blog_image']['label'] = '';
  $handler->display->display_options['fields']['field_blog_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_blog_image']['settings'] = array(
    'image_style' => '140x90',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  /* Field: Content: Library news blog post content */
  $handler->display->display_options['fields']['field_blog_post']['id'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['table'] = 'field_data_field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['field'] = 'field_blog_post';
  $handler->display->display_options['fields']['field_blog_post']['label'] = '';
  $handler->display->display_options['fields']['field_blog_post']['alter']['max_length'] = '180';
  $handler->display->display_options['fields']['field_blog_post']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['field_blog_post']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_blog_post']['settings'] = array(
    'linked_field' => array(
      'linked' => 0,
      'destination' => '',
      'title' => '',
      'target' => '',
      'rel' => '',
      'text' => '',
    ),
  );
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'advocacy' => 'advocacy',
    'booksandbeyond' => 'booksandbeyond',
    'jcpl_kids' => 'jcpl_kids',
    'jcpl_teens' => 'jcpl_teens',
    'library_news' => 'library_news',
  );
  /* Filter criterion: Content: Events tag (field_events_tag) */
  $handler->display->display_options['filters']['field_events_tag_tid']['id'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['table'] = 'field_data_field_events_tag';
  $handler->display->display_options['filters']['field_events_tag_tid']['field'] = 'field_events_tag_tid';
  $handler->display->display_options['filters']['field_events_tag_tid']['value'] = array(
    0 => '54',
  );
  $handler->display->display_options['filters']['field_events_tag_tid']['vocabulary'] = 'events';
  $handler->display->display_options['block_description'] = 'Teen: Event Highlights';
  $export['event_highlights_'] = $view;

  return $export;
}
